runtime: go122

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 1

handlers:
- url: /
  static_files: public/index.html
  upload: public/index.html

- url: /(.*)
  static_files: public/\1
  upload: public/(.*)
